import Head from "next/head";
import styles from "../../styles/Profile.module.scss";
// import Feed from "../Components/Home/Feed";
import OnYourMind from "../../Components/OnYourMind";
import { motion } from "framer-motion";
import UserInfo from "../../Components/Profile/UserInfo";
import EditProfileModal from "../../Components/Modals/EditProfileModal";
import { useEffect, useState } from "react";
import { useData } from "../../Context/DataContext";
import router from "next/router";
import { useAuth } from "../../Context/AuthContext";

export default function UserProfile() {
  const { fetchProfile, profile, userProfile } = useData();
  const [data, setData] = useState({});
  const [status, setStatus] = useState(false);
  const { currentUser } = useAuth();
  const { user } = router.query;

  useEffect(() => {
    async function temp() {
      setStatus(false);
      const res = await fetchProfile(user);
      setData(res);
    }
    if (user !== profile?.username) temp();
    else {
      setData(profile);
      setStatus(true);
    }
  }, [profile]);

  return (
    <>
      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <EditProfileModal />

      <motion.main
        initial={{ opacity: 0, y: 100 }}
        animate={{ opacity: 1, y: 0 }}
        exit={{ opacity: 0 }}
        layout
        className={styles.main}
      >
        <UserInfo data={data} status={status} />
        {status && <OnYourMind />}
        {/* <Feed /> */}
      </motion.main>
    </>
  );
}
