import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import Feed from "../Components/Home/Feed";
import OnYourMind from "../Components/OnYourMind";
import { motion } from "framer-motion";
import router from "next/router";
import { useEffect } from "react";
import { useAuth } from "../Context/AuthContext";
import { useData } from "../Context/DataContext";

export default function Home() {
  const { isLoggedIn } = useAuth();
  const { feed } = useData();

  useEffect(() => {
    if (!isLoggedIn) router.push("/");
  }, [isLoggedIn]);

  return (
    <>
      <Head>
        <title>BumbleBee - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <motion.main
        initial={{ opacity: 0, y: 100 }}
        animate={{ opacity: 1, y: 0 }}
        exit={{ opacity: 0 }}
        layout
        className={styles.main}
      >
        <OnYourMind />
        <Feed data={feed} title="Buzz around you" />
      </motion.main>
    </>
  );
}
