import Head from "next/head";
import styles from "../styles/Landing.module.scss";
import { motion } from "framer-motion";
import Nav from "../Layout/Nav";
import Button from "../Components/Utils/Button";
import router from "next/router";
import { useAuth } from "../Context/AuthContext";
import { useEffect } from "react";

export default function Landing() {
  const { isLoggedIn } = useAuth();

  useEffect(() => {
    if (isLoggedIn) router.push("/home");
  }, [isLoggedIn]);

  return (
    <>
      <Head>
        <title>BumbleBee - Landing</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav />
      <motion.main
        initial={{ opacity: 0, y: 100 }}
        animate={{ opacity: 1, y: 0 }}
        exit={{ opacity: 0 }}
        layout
        className={styles.main}
      >
        <motion.div className={styles.container}>
          <motion.div className={styles.textContainer}>
            <h1>The Perfect place online for your peace of mind</h1>
            <h3>High time we start caring about our mental health online</h3>
            <Button className={styles.button}>Start Buzzing {arrow} </Button>
          </motion.div>
          <motion.div className={styles.imageContainer}>
            <img src="/Hero.png" alt="hero" />
          </motion.div>
        </motion.div>
      </motion.main>
    </>
  );
}

const arrow = (
  <svg
    width="10"
    height="18"
    viewBox="0 0 10 18"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      d="M9.37518 8.29109L2.29975 1.22817C2.18354 1.111 2.04528 1.018 1.89295 0.954538C1.74062 0.891074 1.57722 0.858398 1.4122 0.858398C1.24717 0.858398 1.08378 0.891074 0.931449 0.954538C0.779116 1.018 0.640856 1.111 0.524645 1.22817C0.291818 1.46239 0.161133 1.77922 0.161133 2.10947C0.161133 2.43972 0.291818 2.75656 0.524645 2.99078L6.71252 9.24115L0.524645 15.429C0.291818 15.6632 0.161133 15.9801 0.161133 16.3103C0.161133 16.6406 0.291818 16.9574 0.524645 17.1916C0.640421 17.3097 0.778485 17.4037 0.930838 17.4681C1.08319 17.5325 1.2468 17.566 1.4122 17.5667C1.57759 17.566 1.74121 17.5325 1.89356 17.4681C2.04591 17.4037 2.18398 17.3097 2.29975 17.1916L9.37518 10.1287C9.50207 10.0116 9.60333 9.86957 9.6726 9.71144C9.74186 9.5533 9.77762 9.38254 9.77762 9.2099C9.77762 9.03726 9.74186 8.8665 9.6726 8.70836C9.60333 8.55023 9.50207 8.40815 9.37518 8.29109Z"
      fill="white"
    />
  </svg>
);
