import Head from "next/head";
import styles from "../styles/Profile.module.scss";
import Feed from "../Components/Home/Feed";
import OnYourMind from "../Components/OnYourMind";
import { motion } from "framer-motion";
import UserInfo from "../Components/Profile/UserInfo";
import EditProfileModal from "../Components/Modals/EditProfileModal";
import { useState } from "react";

export default function Profile() {
  return (
    <>
      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <EditProfileModal />

      <motion.main
        initial={{ opacity: 0, y: 100 }}
        animate={{ opacity: 1, y: 0 }}
        exit={{ opacity: 0 }}
        layout
        className={styles.main}
      >
        <UserInfo />
        <OnYourMind />
        <Feed />
      </motion.main>
    </>
  );
}
